In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import seaborn as sns
# Pre-processing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn import decomposition
from sklearn import decomposition, metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
from Hackaton.python.read_pics import get_pics_from_file

In [ ]:
pics_name = os.listdir('Hackaton/data/')
pics_name.remove('pics_LOGINMDP.bin')


## Transform to panda dataset


In [ ]:
data = dict()
for i in range(17):
    data[str(i)] = []
data["name"] = []

for pic_name in pics_name:
    pics_key, info = get_pics_from_file(f'Hackaton/data/{pic_name}')
    for pics in pics_key:
        for i, pic in enumerate(pics):
            data[str(i)].append(pic)
        data["name"].append(pic_name)

df = pd.DataFrame(data)
df.head(6)


In [ ]:
X = df.iloc[:, :-1]
y = df.iloc[:, 17]

print("X shape = " + str(X.shape))
print("y shape = " + str(y.shape))

In [ ]:
# List of name (X)


In [ ]:
# Normalize
normalizer = Normalizer()
X = normalizer.fit_transform(X)

# Standardize
scaler = StandardScaler()
X = scaler.fit_transform(X)






In [ ]:
pca = decomposition.PCA()
pca.fit(X)
plt.figure(figsize=(10,8))
plt.plot(range(1, 18), pca.explained_variance_ratio_.cumsum(), marker='o', linestyle='--')

In [ ]:
minidf = df.loc[(df["name"] == "pics_1.bin") | (df["name"] == "pics_2.bin") | (df["name"] == "pics_5.bin")]
sns.lmplot(x="2", y="6",
  data=minidf,
  fit_reg=False,
  hue='name', # color by cluster
  legend=True,
  scatter_kws={"s": 1}) # specify the point size



In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, shuffle=True)

In [ ]:
# KNN
K = 5

# Create and fit model
neigh = KNeighborsClassifier(n_neighbors=K)
neigh.fit(X_train, y_train)

In [40]:
from sklearn.neighbors import NearestCentroid
clf = NearestCentroid()
clf.fit(X_train, y_train)


NearestCentroid()

In [41]:
# Test
y_pred = clf.predict(X_test)

print(metrics.accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.42463852200721247
[[637  76  42 ...   0   0   0]
 [ 61 137 146 ...   1  12   0]
 [ 69 155 387 ...   0  10   0]
 ...
 [  5   1  15 ... 424   0 346]
 [  2   2  25 ...   2 289   3]
 [  2   1  16 ... 422   0 541]]
                precision    recall  f1-score   support

    pics_0.bin       0.39      0.30      0.34      2144
    pics_1.bin       0.18      0.07      0.10      2022
    pics_2.bin       0.26      0.18      0.22      2105
    pics_3.bin       0.28      0.12      0.17      1961
    pics_4.bin       0.27      0.36      0.31      2636
    pics_5.bin       0.33      0.20      0.25      2176
    pics_6.bin       0.13      0.16      0.14      1943
    pics_7.bin       0.26      0.18      0.22      2080
    pics_8.bin       0.26      0.14      0.18      2083
    pics_9.bin       0.37      0.67      0.47      2001
    pics_A.bin       0.40      0.16      0.23      1860
    pics_B.bin       0.23      0.23      0.23      1893
    pics_C.bin       0.45      0.82      0.58      1968
 pi

In [ ]:
# Test
y_pred = neigh.predict(X_test)

print(metrics.accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

In [ ]:
from sklearn.metrics import plot_confusion_matrix
# Plot non-normalized confusion matrix
disp = plot_confusion_matrix(neigh, X_test, y_test,
                             cmap=plt.cm.Blues,
                             normalize='true')
disp.ax_.set_title('Normalized confusion matrix')

In [ ]:
# Test
pics_key, info = get_pics_from_file(f'Hackaton/data/pics_LOGINMDP.bin')
predictions = []
predictions_proba = []
for pics in pics_key:
    to_predict = normalizer.transform(pics.reshape(1, -1))
    to_predict = scaler.transform(to_predict)
    key = neigh.predict(to_predict)[0]
    if key != 'pics_NOKEY.bin':
        predictions.append(key)
        predictions_proba.append(neigh.predict_proba(to_predict)[0])


In [ ]:
for pic_name in pics_name:
    print(f'{pic_name} : {predictions.count(pic_name)}')

In [ ]:
reconstruct = res = list(filter('pics_NOKEY.bin'.__ne__, predictions))
print(reconstruct)

In [ ]:
print(predictions)
